// Code generated by "generate_embedded"; DO NOT EDIT.
package main

var indexHTML = "<html>\n<title>Requester</title>\n<form method=\"POST\">\n    <input name=\"url\" placeholder=\"url\">\n    <button>Send</button>\n</form>"
