//+build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io/ioutil"
	"log"
)

func main() {
	if err := generate(); err != nil {
		log.Fatal(err)
	}
}

func generate() error {
	b, err := ioutil.ReadFile("index.html")
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	fmt.Fprintf(&buf, `// Code generated by "generate_embedded"; DO NOT EDIT.
package main
var indexHTML = %q`, b)
	fmtbuf, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	return ioutil.WriteFile("embedded.go", fmtbuf, 0644)
}
